name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.0
    - name: Restore dotnet dependencies
      run: |
        cd CSharp.Infrastructure/CSharp.Infrastructure
        dotnet restore
    - name: Build
      run: |
        cd CSharp.Infrastructure/CSharp.Infrastructure
        dotnet build --no-restore
